AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: SQS to SNS

Parameters:
  SQSQueueArn:
    Type: String
    Description: ARN of the SQS queue.

Resources:
  Function:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      CodeUri: /bootstrap
      Handler: bootstrap
      Runtime: provided.al2
      Architectures:
        - x86_64
      Timeout: 10
      Policies:
        - AWSLambda_FullAccess
        - AWSLambdaSQSQueueExecutionRole
        - AmazonSNSFullAccess
        - AmazonSQSFullAccess
      AutoPublishAlias: live
      DeploymentPreference:
        Type: Canary10Percent10Minutes
      Events:
        MySQSEvent:
          Type: SQS
          Properties:
            Queue: !Ref SQSQueueArn
            BatchSize: 10
